#adapted from example in docker documentation
version: '3'

services:
   redis:
      image: "redis:latest"
   web:
      build: .
      volumes:
         - .:/code
      ports:
         - 8000:8000
      command: python /code/mysite/manage.py runserver 0.0.0.0:8000
      links:
         - redis
