# Generated by Django 3.1.4 on 2020-12-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
